<?php
/**
 * VERSION 1.0
 * Updated 5/31/2016
 *
 * Version 1.0.1
 * Updated 3/28/2022
 */
// Todo: Change Procedural process to OOP
ob_start();
require_once("../globals/globals.php");
$filename = GENERATED_FILES_DIR . "geoip_cfs_webhost_ipv4.txt";

$mysqli = mysqli_connect(
    DATABASE_ROLES['default']['host'],
    DATABASE_ROLES['default']['user'],
    DATABASE_ROLES['default']['password'],
    DATABASE_ROLES['default']['database']
);
if ($mysqli->connect_errno) {
    echo "Failed to connect to MySQL: (" . $mysqli->connect_errno . ") " . $mysqli->connect_error;
}

/*
$mysqli->real_query("SELECT
blocks_isp.network_cidr,
blocks_isp.isp,
blocks_isp.organization
FROM
blocks_isp
WHERE
blocks_isp.isp = 'Google' OR
blocks_isp.organization = 'ColoCrossing' OR
blocks_isp.organization = 'B2 Net Solutions' OR
blocks_isp.organization = 'Privax' OR
blocks_isp.organization = 'Softlayer'
");
*/

echo "Build list of Web Hosting / Proxy Providers<hr>\r\n";

$mysqli->real_query('SELECT provider_name FROM cfs_hosts');
$res = $mysqli->use_result();
//echo "Result set order...\n";

$sql_line = "(";
while ($row = $res->fetch_assoc()) {
    //$line .= "" . $row['provider_name'] . " " . $row['isp'] . "|" . $row['organization'] . "\r\n";
    $sql_line .= '
    "' . $row['provider_name'] . '",';
    //echo $row['provider_name'] . "<br>\r\n";
}
$sql_line = substr($sql_line,0,-1);
$sql_line .= ")";
//echo $sql_line;



$mysqli->real_query('SELECT
blocks_isp.network_cidr,
blocks_isp.isp,
blocks_isp.organization
FROM
blocks_isp
WHERE 
      blocks_isp.isp IN ' . $sql_line . ' 
    OR 
      blocks_isp.organization IN ' . $sql_line  );


/*
$mysqli->real_query('SELECT
blocks_isp.network_cidr,
blocks_isp.isp,
blocks_isp.organization
FROM
blocks_isp
WHERE blocks_isp.isp IN
("Computer Sciences Corporation",
"Google",
 "ColoCrossing",
 "B2 Net Solutions",
 "Privax",
 "Softlayer",
"Involta",
"Yesup Ecommerce Solutions",
"GINERNET",
"Linode",
"Contina",
"Alentus Internet Services",
"Peg Tech",
"Avante Hosting Services",
"Leaseweb Germany GmbH (previously netdirekt e. K.)",
"Customer VPS services located in New York City, US",
"colocation TCTEL",
"NewMedia Express Pte Ltd, Singapore Web Hosting",
"Hugeserver Network, LLC",
"HugeServer Networks, LLC",
"Hoyos Consulting LLC",
"Amanah Tech",
"Swiftway Sp. z o.o.",
"LogicWeb Inc",
"Netco Solutions Ltd",
"Commercial Media Corporation",
"Dedicated servers",
"Staminus Communications",
"Abovenet Communications",
"Secured Private Network",
"Amazon Technologies",
"Amazon.com Tech Telecom Amazon Technologies",
"Amazon.com Tech Telecom",
"Amazon.com",
"Amazon",
"AMAZON",
"Atlantic.net",
"Amazon.com Tech Telecom",
"Amazon Data Services Ireland",
"Amazon Technologies",
"Amazon Web Services, LLC",
"Greenhost BV",
"E.I. du Pont de Nemours and Co.",
"New Jersey International Internet Exchange LLC",
"WholeSale Internet",
"SIA Digitalas Ekonomikas Attistibas Centrs",
"Dacentec",
"Network Operations Center",
"Microsoft Hosting",
"ColoCrossing",
"Corporate Colocation",
"DataShack, LC",
"Leaseweb USA",
"Rica Web Services",
"5280 Enterprises LLC.",
"Versaweb, LLC",
"FDCservers.net",
"VPMANAGE",
"Interoute Communications Limited",
"OVH Hosting",
"Fastweb",
"ServeByte",
"Virtua",
"SingleHop",
"Webair Internet Development Company",
"ServeByte",
"Nodes Direct",
"Pools for Dedibox Customers",
"SingleHop",
"Web Africa Proxy",
"OVH Systems",
"DFW Datacenter",
"MTW.RU dedicated/hosting servers",
"JSC Mediasoft ekspert",
"fast IT Colocation",
"Gmo Cloud America",
"Fiber Upload Srl",
"myLoc managed IT AG",
"Simply Transit Ltd",
"Hetzner Online AG",
"Hosting Solutions International",
"ZettaGrid",
"HOSTING90 systems s.r.o.",
"ETB",
"QuickPacket, LLC",
"Ubiquity Server Solutions Los Angeles",
"Information Technology Company (ITC)",
"Interprovider Limited",
"Multacom Corporation",
"OVH Ltd",
"Enzu",
"Hurricane Electric",
"ANEXIA Internetdienstleistungs GmbH",
"Cogent Communications",
"Iomart Hosting Limited",
"Cloud Customers",
"Colo at 55, LLC",
"ColoCrossing",
"Psychz Networks",
"Server Axis Corporation",
"Dedicated Server Hosting",
"Conjoinix Technologies Pvt. Ltd.",
"Server Block",
"Query Foundry, LLC",
"GHOSTnet GmbH",
"EasyTech",
"DataPipe",
"FASTNET",
"ServeTheWorld AS",
"HugeServer Networks, LLC",
"Private Enterprise Firma Fenix VT",
"UK Dedicated Servers Limited",
"Unix-Solutions BVBA",
"LeaseWeb",
"IPTelligent LLC",
"SoftLayer Technologies",
"Softlayer",
"SoftLayer Dutch Holdings B.V.",
"Server Pronto",
"inAsset Networks, S.L.",
"Free SAS",
"FD Networks",
"Redstation Limited",
"Host-telecom-net",
"SingleHop BV",
"Hosting Internet Hizmetleri Sanayi ve Ticaret Anon",
"DirectSpace Networks, LLC.",
"Portlane Networks AB",
"Transip B.V.",
"Interserver",
"Webhosting.Net",
"Ubiquity Server Solutions Seattle",
"Incero LLC",
"Ninefold",
"Solar VPS",
"Private Layer Inc",
"Katalyst Partners, LLC",
"OVH SAS",
"Infinite Technologies Limited",
"Microsoft Corporation",
"Silicon Valley Web Hosting",
"Wowrack.com",
"WebNX",
"AltusHost B.V.",
"NetVision",
"FortressITX",
"Hosting Services",
"Input Output Flood LLC",
"Columbus Networks USA",
"HostDime.com",
"SupremeBytes,LLC",
"Powerhouse Management",
"Hostingsource",
"EBL Global Networks",
"Database by Design, LLC",
"CtrlS Datacenters",
"Carat Networks",
"Fast Serv Networks, LLC",
"Kvchosting.com LLC",
"WeHostWebSites.com",
"Ubiquity Server Solutions Dallas",
"B2 Net Solutions",
"RackCentral Pty Ltd",
"Ubiquity Server Solutions New York",
"Privax Limited",
"Unlimited Net, LLC",
"Google",
"Google Cloud",
"HOST1PLUS Brazil",
"Limestone Networks",
"Avante Hosting Services",
"iWeb Technologies",
"Hosting Solutions",
"Kddi Corporation",
"Secured Servers LLC",
"Sean Isley",
"eNET",
"Nobis Technology Group, LLC",
"iWeb Technologies",
"Ubiquity Server Solutions Atlanta",
"WANSecurity",
"Choopa, LLC",
"Angel Drops",
"Ubiquity Server Solutions New York",
"Netrouting",
"EGIHosting",
"Steadfast Networks",
"Continuum Data Centers, LLC.",
"Open Computer Network",
"VolumeDrive",
"Hostwinds LLC.",
"Hostwinds LLC",
"Sharktech",
"Take 2 Hosting",
"Netelligent Hosting Services",
"HostRocket Web Services",
"TELECOM ITALIA SPARKLE S.p.A.",
"ServiHosting Networks S.L.",
"EGIHosting",
"Oversun Ltd",
"Internet-Hosting Ltd",
"OneAsiaHost",
"Megahostasn Mega Host Limitedb",
"Global Crossing",
"Gigas Hosting Usa, LLC",
"Gigas Hosting S.l",
"Gigas Hosting S.l.",
"HostDime.com.br Data Center",
"AltusHost",
"Hostwinds LLC.",
"Kvchosting.com LLC",
"Privax LTD",
"HP Hosting",
"Felicity Netbrella Corporation",
"Astute Hosting",
"Avante Hosting Services",
"NTT Network Core in LE hosting",
"WeHostWebSites.com",
"Melbourne Server Hosting Ltd",
"Level 3 Communications",
"Oversun Ltd",
"Iliad Hosting",
"Free SAS",
"Online S.a.s.",
"RapidSwitch Ltd",
"Iomart Hosting Limited",
"AltusHost Sweden Network",
"NOC4Hosts",
"NewMedia Express Pte Ltd.",
"Singapore Web Hosting Se",
"ServiHosting Networks S.L.",
"Unlimited Web Hosting UK LTD",
"RamNode LLC",
"jane m martin",
"Servepath",
"The Optimal Link Corporation",
"Poundhost customer server",
"Simply Transit Ltd",
"CrystalTech Web",
"Black Oak Computers Inc - Miami",
"Ericyhost - Ericsson North America Managed Service",
"Hosteam S.c.",
"XLHost.com","Megahostasn Mega Host Limited",
"Allhostshop.com",
"Conectiva",
"Hosting Operator eServer.ru Ltd.",
"Serverhousing - Hosting - IT-Services",
"Ovh Hosting Oy",
"Hostemo Technology Sdn Bhd",
"Rackspace Hosting",
"nLayer Communications",
"GIGLINX",
"DurableDNS, LLC",
"EGIHosting",
"Host Virtual",
"Reliablehosting.com",
"Megahostasn Mega Host Limited",
"CrystalTech Web Hosting",
"Hostemo Technology Sdn Bhd",
"WestHost",
"Megahostasn Mega Host Limited",
"FranceCentralHosts",
"Real Hosts Limited",
"Cloudhost Limited",
"Biznes-Host.pl sp. z o.o.",
"Myhosting",
"JaroNet s.r.o., Hostim",
"Hostspace - Hostspace Networks LLC",
"NexteCloud L.L.C.",
"Mochahost.com",
"Host Europe GmbH",
"SiteNet Host",
"HostForWeb",
"NewMedia Express Pte Ltd.",
"Hostdime.com UK client",
"HostDime Limited",
"Neo Telecoms S.A.S.",
"Gigabit Hosting",
"Fornex Hosting S.L.",
"LayerIP - UK hosting division infrastructure",
"Cyberghost S.R.L. IP Network",
"RimuHosting",
"TM-VADS DC Hosting",
"NTT Europe Web Hosting - Frankfurt",
"HOST1PLUS VPS servers at Brazil location",
"Fasthosts Internet Limited - UK\'s largest web host",
"Fasthosts Internet",
"Fast Hosts LTD",
"NTT Europe Web Hosting - Frankfurt",
"AT&T Webhosting Amsterdam IDC",
"Host-Telecom.com",
"OVH Hosting Limited",
"GoDaddy.com, LLC",
"Web Phase Limited",
"Go Daddy Netherlands B.V.",
"VegasNAP, LLC",
"Black Oak Computers Inc - San Francisco Reliablehosting.com",
"TC TEL hosting",
"QuadraNet",
"DataShack, LC",
"Nobis Technology Group, LLC",
"Ubiquity Server Solutions Chicago",
"Nobis Technology Group Phoenix",
"Iptripleplay Ltd",
"George Kontostanos (Planet Maars)",
"Tranquil Hosting",
"Sophidea",
"Alpheus Data Services, L.L.C.",
"incubatec GmbH - Srl",
"Incubatec GmbH - SRL",
"Freenet Ltd.",
"Triple T Internet Company Limited",
"PleskLogin Net",
"Microglobe LLC",
"HOSTINGER",
"Microsoft Hosting",
"Gandi Dedicated Hosting Servers",
"AFNCA",
"DME Hosting LLC",
"TM VADS DC Hosting",
"UDomain Web Hosting Company",
"Portland Internet Hosting LLC",
"JMF, Web Hosting Company, Japan",
"GorillaServers",
"Directspace Networks",
"XL Internet Services B.V.",
"InstaVPS",
"Digiweb ltd",
"Trit Networks, LLC",
"Sc Fx Software Srl",
"Joyent",
"Telecom Argentina S.A.",
"Pegtechinc - Peg Tech",
"LRG, Inc.",
"Infodoor Networking (Pty) Ltd",
"CMC Telecom Infrastructure Company",
"Antonio Santos",
"AS JSC KazTransCom",
"Nobis Technology Group, LLC",
"UpCloud Cloud Servers",
"Crissic Solutions, LLC",
"Sigmatic Oy",
"Netinternet Bilgisayar ve Telekomunikasyon San. ve",
"Turnkey Internet",
"AUNA - CTC",
"Voxel Dot Net",
"VPS Cheap",
"ReInfoCom Ltd.",
"Rackspace Cloud Servers",
"HostHatch, Inc",
"SolidHost",
"proXPN Direct LLC",
"Black Oak Computers Inc - San Francisco",
"Host-Telecom.com s.r.o.",
"Nexeon Technologies",
"jan-erik_hintikka",
"Cloud Servers Cell 0001-0003 IAD3",
"Cloud Servers (ORD)",
"Rackspace Cloud Servers IP Space",
"23Media GmbH",
"Inmotion Group",
"AT&T Synaptic Cloud Hosting",
"Aruba S.p.A.",
"Serveryou",
"Krypt Technologies",
"Yomura Corporation",
"Digital United Inc.",
"China Unicom Zhejiang",
"D-hosting die Rackspace & Connectivity GmbH",
"Customer VPS services located in Falkenberg",
"Neterra servers infrastructure",
"Neterra Ltd.",
"Server Serveis i Productes Informatics, S.L.",
"IP ServerOne Solutions Sdn Bhd",
"Syniverse Technologies, LLC",
"Hosted Data Solutions, LLC",
"Data Return",
"KDDI Web Communications Inc.",
"Colo4, LLC",
"EHOSTIDC",
"Cloudsigma Ag",
"Googlebot",
"ilika.net LLC",
"Hexaware Technologies Limited",
"IT7 Networks",
"AWB-NET Agnieszka Barzdo",
"phpwebhosting.com, LLC",
"ioko customer hosting block 2 - TH",
"Webhostingbuzz.com",
"Fastvps Eesti Ou",
"Black Fox Limited",
"CentriLogic",
"Centrilogic",
"CloudRadium L.L.C",
"Dimension Data Cloud Solutions",
"ColoUp",
"SolidTools Technology",
"LeaseWeb B.V.",
"Microsoft bingbot",
"1&1 Internet",
"Digital Ocean",
"DigitalOcean",
"Privax",
"KW Datacenter",
"ReliableSite.Net LLC",
"Mileweb PacketExchange",
"Mileweb",
"Hostspace Networks LLC",
"ClearDDoS Technologies",
"Hostlocation Ltda",
"S.C. Everhost S.R.L.",
"HOST1PLUS hosting services. Brazil.",
"Astimp Consulting SRL",
"Conjoinix Technologies Pvt. Ltd.",
"Global Frag Networks",
"Websecure",
"Landis Holdings",
"Conceptual Mindworks",
"Cbeyond Communications",
"Friedlander Cherwon Capper LLP",
"TNCI",
"IPNetZone",
"Airband Communications",
"Zimcom Network Solutions",
"OLM, LLC",
"DC74 LLC",
"Virtuzo",
"Vivid Hosting",
"Burstfire Networks Ltd",
"INTERNEXT 2000 s.r.o.",
"Micfo, LLC.",
"Simply Transit Ltd",
"IncoNet Data Management sal",
"Microsoft Azure",
"Microsoft Corp",
"Netmagic Datacenter Mumbai",
"Netmagic Datacenter",
"Net Design SRL",
"DoclerWeb Kft.",
"1&1 Internet AG",
"Virtual Server hosting",
"Makonix SIA",
"Atlantic.Net - Dallas, LLC.",
"GlobalNet",
"SFR",
"VPS-clients",
"Pallada Web Service LLC",
"Long Van Soft Solution JSC",
"GMO Internet, Inc.",
"Hexabyte",
"SoftLayer Dutch Holdings BV",
"GigaSpaces Technologies",
"Host Palace Internet Services",
"Serverius Holding B.V.",
"DFI Service SA",
"INTERNEXT 2000 s.r.o.",
"Cogetel Online",
"Dacentec",
"Telentia Enterprise Client",
"Anonymous Proxy",
"CIS NEPHAX",
"VooServers Ltd",
"Zen Systems Hosting",
"Zen Systems A/S",
"MadeIT",
"Azuria",
"RackCentral Networks",
"Gigabit Hosting Sdn Bhd",
"Telentia",
"B2 Net Solutions",
"Privax Limited",
"Ubiquity Server Solutions Atlanta",
"iWeb Technologies",
"NetStack-AS",
"Digital Energy Technologies Chile Sp",
"Netbrella Corporation",
"CIS NEPHAX",
"Micfo, LLC.",
"InstaVPS",
"Waveform Technology, LLC",
"THOR Data Center ehf",
"SC Fastweb SRL",
"SIS Group Datacentre Sydney",
"iomart Group PLC",
"Contabo GmbH",
"Net-style Atarim Ltd",
"Citylink Fiber Holdings",
"GINERNET",
"Deninet KFT",
"Core-Backbone GmbH",
"Ecatel Network",
"Oy Crea Nova Russia LTD",
"Private Layer Inc",
"Netco Solutions Limited",
"Ecatel LTD",
"Uab Duomenu Centras",
"IPSERVERONE - Colocation & Dedicated Servers",
"BetterServers (BETTE-38)",
"Ace Data Centers",
"Xt Global Networks Ltd.",
"Dedicated Servers Ip Pool",
"ZAO National Telecommunications",
"Net for VPS servers.",
"United Gameserver GmbH",
"Sub-Allocation myLoc",
"VDC",
"VpsQuan L.L.C.",
"XeVPS L.L.C",
"Sun Network (Hong Kong) Limited",
"VPSLAND",
"Global Net Access, LLC",
"Webfusion Internet Solutions",
"VPS",
"Hurricane Internet",
"tw telecom holdings",
"WWW Ibercom Net",
"National Computer Systems Co Ltd",
"HiNet",
"MTN Network Solutions Pty Ltd",
"Procono S.A.",
"Soltia Consulting SL",
"Power Up Hosting",
"VMware",
"TekSavvy Solution",
"Leaseweb Germany GmbH",
"NewMedia Express Indonesia Operation",
"TurkNet Iletisim Hizmetleri A.S.",
"IP-Converge Data Center",
"IP-Converge, Internet Data Center.",
"HOST1PLUS OpenVZ VPS services.",
"Netstack Ltd",
"Digital Energy Technologies Chile SpA",
"UK2 - Ltd",
"OppoBox",
"Leaseweb Asia",
"Leaseweb Deutschland GmbH",
"LeaseWeb Network B.V.",
"LeaseWeb Netherlands B.V.",
"Secure Internet LLC",
"Infolink Global Corporation",
"CyrusOne LLC",
"Websitewelcome.com",
"Terrenap Data Centers",
"Websense Hosted Security Network",
"SurfControl",
"FortaTrust USA Corporation",
"Microsoft",
"FreeBit Co.,Ltd.",
"MAROSNET Telecommunication Company LLC",
"Mojohost VL401 3NGNETWORKS",
"Mojohost",
"Unithost Internet B.V.",
"Netorn, hosting & colocation",
"Netorn LLC",
"Alphaomegahosting-colo",
"UK Webhosting Ltd",
"Fast2host Ltd",
"FranTech Solutions",
"Locaweb Servi xE7os de Internet S/A",
"Query Foundry, LLC",
"VTX Services SA",
"InfraDMS",
"Micfo, LLC.",
"Miami Cloud Hosting",
"OppoBox",
"AccelerateBiz",
"Host1free.com - Free Hosting & Vps & Cloud-service",
"Trusov Ilya Igorevych",
"Transit Telecom LLC",
"Atomohost LLC",
"AVAST Software s.r.o.",
"Unified Layer",
"Peer 1 Network (USA)",
"B2 Net Solutions VPS CLIENTS",
"Joe\'s Datacenter, LLC",
"Roya Hosting LLC",
"HostMySite",
"World Wide Web Hosting, LLC",
"Serverdroid LLC",
"OOO Network of data-centers Selectel",
"SourceDNS",
"Ideal Hosting Sunucuninternet Hiz. Tic. Ltdsti",
"Clouditalia Telecomunicazioni S.p.A.",
"Idealhosting Sunucu Internet Hiz. Tic. Ltd Sti",
"Mahsum Celik trading as ServerPlus Internet Sunucu",
"Net3",
"Aventice LLC",
"QuickPacket, LLC",
"GOSTARESH-E-ERTEBATAT-E MABNA COMPANY (Private Joi",
"Datacenter IP, LLC",
"ColoCenter b.v.",
"HP Hosting",
"VMware",
"VMware UK Ltd.",
"Liquid Web",
"Hetzner Online GmbH",
"Hetzner Online AG",
"Tomato Web (PVT) Limited",
"Advan Technologies LLC",
"IBM Corporation",
"ThePlanet.com Internet Services",
"M5 Computer Security",
"7Host Web Hosting",
"Solido Hosting A/S",
"Iliad Hosting",
"Hosting Services",
"Hostinger International Limited",
"Avante Hosting Services",
"Dedicated Server Hosting",
"Iomart Hosting Limited",
"Hostspace Networks LLC",
"HP Hosting",
"HostDime.com",
"7Host Web Hosting",
"Spartan Host",
"Host Sailor Ltd.",
"HostPalace Network Services",
"HostHatch",
"Web hosting provider and ISP connectivity.",
"HostUS",
"HostUS Solutions LLC",
"Hostigation",
"JaroNet s.r.o., Hostim",
"Hostkey B.v.",
"HostDime.com.mx S.A. de C.V.",
"HostDZire Web Services Pvt. Ltd.",
"Aruba GmbH Cloud Network",
"Hostspace Networks LLC",
"UOL Cloud Computing",
"Host Lincoln Limited",
"HostDime Data Center Services PVT",
"Nodistro IT, LLC",
"SupremeBytes, LLC",
"CloudMosa",
"DedFiberCo",
"Cloud Sigma",
"UPC Ceska Republica, s.r.o.",
"UPS Austria Gmbh",
"WBS Connect, LLC",
"Areti Internet Ltd",
"Falco Networks B.V.",
"Alentus Corporation"
"Leaseweb Asia Pacific pte. ltd.",
"Iomart",
"RamNode LLC",
"Cncservers LLC",
"SimpleLink LLC",
"Cty co phan ha tang vien thong CMC",
"layer 2 -Customer Nework of VTDC",
"Optimate-Server",
"M247 Ltd",
"180Servers.com",
"Oso Grande IP Services, LLC",
"KeepYourIP",
"C7 Data Centers",
"DataCenter One",
"Trend Micro Incorporated",
"Athenix",
"River City Internet Group (Primary Networks)",
"Arvixe, LLC",
"Quantil",
"Easyhost BVBA",
"Cyber Futuristics India Pvt",
"CoreSpace",
"Micfo, LLC.",
"Onvoy",
"DepoDataCenter",
"Netsoftware LLC",
"Kalamazoo RESA",
"RACK59 Partners, LLC",
"Drake Holdings LLC",
"Handy Networks, LLC",
"Hosting Solution",
"Univera Network",
"InMotion Hosting",
"A2 Hosting",
"ComfortHost",
"Host Wagon LLC",
"Peer 1 Dedicated Hosting",
"Server Central Network",
"White Sands Hosting",
"QuickWeb Technologies LLC",
"Server Central Network",
"Telx",
"Reprise Hosting",
"Eonix Corporation",
"Lowest Host/Empire Technology LLC",
"EvolveIP, LLC",
"New Dream Network, LLC",
"Link Telecom LLC",
"Siteserver Hosting",
"Hostway Corporation",
"UK2.NET",
"OC Hosting",
"Virtual Internet (UK) Limited",
"JCHost Internet Services, LLC",
"Arachnitec",
"HostSlim BV",
"Total Server Solutions L.L.C.",
"M247",
"Micron21-Melbourne-Datacentre",
"Petersburg Internet Network",
"PenTeleData",
"hiQ Data Corporation",
"Six Degrees Managed Data Limited",
"Nexlogic Telecommunications Network",
"Automated Data Systems",
"4D Data Centres",
"DataYard",
"Windstream Hosted Solutions, LLC",
"AFConnect",
"Melbourne Server Hosting",
"QWK.Net Hosting",
"Hostgator.com LLC",
"Portlane Networks",
"SIMPLEXHOST-AS",
"Alexhost Srl",
"Normhost Sarl",
"Simplexhost sp. z o.o.",
"UK Webhosting",
"Axxess Networks",
"Afrihost",
"Elastichosts Ltd",
"Root Level Technology, LLC",
"Ransom IT Trust",
"MATI",
"HostRocket.com",
"DotBlock.com",
"Hosting Shop",
"DATAREALM Internet Services",
"Interscale",
"Crucial Paradigm Pty Ltd",
"Interhost Communication Solutions",
"Resilans AB",
"Areti Internet",
"IPVanish",
"Bandcon",
"Mudhook Marketing",
"Mudhook Marketing Ashburn IP Block",
"Eweka Internet Services B.V.",
"Highwinds Network Group",
"CityLink Fiber Holdings, Inc.",
"netirons",
"Fevvo",
"CachedNet LLC",
"Contina",
"Border Technology, LLC",
"Bezeq International",
"Hakan Erdem",
"Inter Connects Inc",
"Core NAP, L.P.",
"Micro Incorporated",
"Pp Sks-lugan",
"home.pl S.A.",
"Virtual Citadel Inc.",
"BroadRiver Hosting",
"BroadRiver",
"1st Class Hosting, LLC",
"A2 Hosting",
"ACENS_AS (Spain) Hosting, housing and VPN services",
"Activehost-ru",
"ADMHOST",
"Adulteuhost",
"Advancedhosters",
"AGARIK provide WEB, Servers Hosting and dedicated",
"Altushost-net",
"Arkbhosting",
"As-cloudhosting",
"ASBHOST B-Host.it Internet Services",
"ASEUHOST",
"Asghostnet",
"Astute Hosting",
"Asvpshosting",
"Atomohost-dc1",
"ATT-EMEAIDC-AMS1-AS AT&T Webhosting Amsterdam IDC",
"Avante Hosting Services",
"Besthosting",
"Beyond Hosting, LLC",
"BHOST",
"Bird Hosting",
"By-hosting",
"Canhost",
"Carpathia Hosting",
"Content Provider and Hosting Services",
"Corporacion Hostarica S.A.",
"Cybercom Hosting",
"Danhost-dk",
"Datenhosting",
"Dedicated servers, colocation, hosting.",
"DGCHost.Net",
"Dhosting-net",
"Dialhost Internet Ltda.",
"Digiweb Advanced Hosting Limited",
"Dinahosting",
"DNHOST",
"DREAMHACKHOSTING Dreamhack - The worlds largest co",
"Easyhost Solution Limited",
"Easyhost-colo",
"EGIHosting",
"Elitehosting",
"Excellent-hosting",
"Extrahost",
"Extrahost-sk",
"Fasthost",
"FERAL Feral Hosting",
"Flamehosting",
"FREEHOST",
"Gigabit Hosting Sdn Bhd",
"GIGAHOST",
"Globalhost-bosnia",
"Globalhosting",
"GMHOST",
"GPLHost LLC",
"Greenhost",
"Grupohost Comunicacao Multimidia Ltda",
"H4hosting",
"Hoopla Hosting Limited",
"Host Color",
"Host Duplex, LLC",
"Host Networks",
"Host Revenda",
"Host Virtual",
"Host-telecom",
"Host1Plus",
"Hostasaurus",
"Hostbasket-backbone",
"Hostcamp",
"Hostcentral",
"HostDime.com",
"HostDime.com.br Data Center",
"Hostdzire",
"Hosteam",
"Hosted Backbone",
"Hosterov",
"Hosteurope",
"Hostex Hostex",
"Hosting operations",
"Hosting Services",
"Hosting Solution",
"HOSTING90 systems s.r.o.",
"Hostinger",
"Hostiserver",
"Hostit-as-nn",
"Hostkey",
"HOSTLINE",
"Hostlocation Ltda",
"HostManager",
"HostMySite",
"HOSTNET",
"Hostpoint",
"Hostpro",
"HostRocket.com",
"Hostserver GmbH",
"HOSTSLIM",
"HostUS",
"Hostway Corporation",
"Hostway Services",
"Hostwinds LLC.",
"HYPERHOSTING Georgios Vardikos trading as HYPERHOS",
"Ihost Solutions Pty",
"iHosting Servicios Internet Ltda.",
"INHOSTED",
"InterBS S.R.L. (BAEHOST)",
"Interhost",
"Interhost Pacific Pty Ltd t/a Intervolve.",
"IPHOST .GR IpDomain",
"Ippon_hosting",
"ISM eCompany Hosting Services",
"ISP and web hosting.",
"Itshosted",
"JCHost Internet Services, LLC",
"Kvchosting.com LLC",
"LCHOST",
"Lightpoint Colocation & Hosting LLC",
"LINQHOST",
"LLHOST",
"Localhost_as",
"Lowest Host/Empire Technology LLC",
"Managedhosting",
"Media-Hosts",
"MIROHOST Web hosting, datacenter and domain names",
"Mojhost-eu",
"MOJOHOST",
"Multihost",
"Multihousehosting",
"My Hosted Internet",
"My-hosted-internet",
"Netelligent Hosting Services",
"Nethostingtech",
"Network of IBM E-business Hosting Delivery",
"NSI Hosting",
"OC Hosting",
"Packet Host",
"Peak Web Hosting",
"Peterhost-piter",
"Pidginhost",
"PRTSYSTEMS PRT Systems Ltd (Clearhost Transit AS)",
"QHOSTER",
"QUADHOST",
"QWK.Net Hosting",
"Rackhosting",
"Rackspace Hosting",
"RAM Host",
"Realhosts",
"Redhosting",
"Reliable Hosting Services",
"Reliablehosting.com",
"Rethem Hosting LLC",
"Routed-Hosting",
"Rucenter-hosting",
"Sadecehosting-Com",
"SAFEHOSTNET Colocation center in Geneva",
"Safehosts",
"SiteHost New Zealand",
"Skhosting-eu",
"Spartanhost",
"Superhost-pl",
"SureHosting Internet Solutions",
"Systemhost",
"Telx Hosting",
"Terrahost_as",
"Tranquil Hosting",
"Tsukaeru.net, Web Hosting Company, Japan",
"UDomain Web Hosting Company",
"UK Dedicated Servers, Hosting and Co-Location",
"UKHOST4U",
"Unic-hosting",
"UNITEL Unitel - Fast reliable hosting",
"Unithost",
"Velocihost",
"Ventelohosting",
"Venzohosting",
"Vivid Hosting",
"Vmhosting-ua",
"Vmhosts-london",
"Voicehost",
"Vshosting",
"WEB4CE webhosting",
"WestHost",
"White Sands Hosting",
"XHOSTING",
"Zappie Host",
"Zglobalhost Ltda.",
"Zimba Host",
"Anycast cloud",
"Apptocloud",
"Arubacloudltd",
"As-cloudhosting",
"As-cloudity",
"As_tcpcloud",
"BELCLOUD",
"Bigstep-cloud",
"Bulletproof, Mission Critical Cloud",
"Cisco Systems Cloud Division",
"Cloud 9 Internet",
"Cloud Comunicacoes Ltda Me",
"Cloud Earth Pty",
"Cloud Registry Pty",
"Cloud Scale Limited",
"Cloud Xpress",
"CLOUD-DK",
"Cloud.IT Services Limited",
"Cloud2nube, S.A.",
"CloudAccess.net, LLC",
"CLOUDATA",
"Cloudcenter",
"CLOUDCORE CloudCore.IO",
"Clouddc",
"Cloudddos Technology Co.,limited",
"Merit Network",
"DHMS Ltd",
"FORTHnet SA",
"BigTip",
"Google",
 "ColoCrossing",
 "B2 Net Solutions",
 "Privax",
 "Softlayer",
"Involta",
"Yesup Ecommerce Solutions",
"GINERNET",
"Linode",
"Contina",
"Alentus Internet Services",
"Peg Tech",
"Avante Hosting Services",
"Leaseweb Germany GmbH (previously netdirekt e. K.)",
"Customer VPS services located in New York City, US",
"colocation TCTEL",
"NewMedia Express Pte Ltd, Singapore Web Hosting",
"Hugeserver Network, LLC",
"HugeServer Networks, LLC",
"Hoyos Consulting LLC",
"Amanah Tech",
"Swiftway Sp. z o.o.",
"LogicWeb Inc",
"Netco Solutions Ltd",
"Commercial Media Corporation",
"Dedicated servers",
"Staminus Communications",
"Abovenet Communications",
"Secured Private Network",
"Amazon Technologies",
"Amazon.com Tech Telecom Amazon Technologies",
"Amazon.com Tech Telecom",
"Amazon.com",
"Amazon",
"AMAZON",
"Atlantic.net",
"Amazon.com Tech Telecom",
"Amazon Data Services Ireland",
"Amazon Technologies",
"Amazon Web Services, LLC",
"Greenhost BV",
"E.I. du Pont de Nemours and Co.",
"New Jersey International Internet Exchange LLC",
"WholeSale Internet",
"SIA Digitalas Ekonomikas Attistibas Centrs",
"Dacentec",
"Network Operations Center",
"Microsoft Hosting",
"ColoCrossing",
"Corporate Colocation",
"DataShack, LC",
"Leaseweb USA",
"Rica Web Services",
"5280 Enterprises LLC.",
"Versaweb, LLC",
"FDCservers.net",
"VPMANAGE",
"Interoute Communications Limited",
"OVH Hosting",
"Fastweb",
"ServeByte",
"Virtua",
"SingleHop",
"Webair Internet Development Company",
"ServeByte",
"Nodes Direct",
"Pools for Dedibox Customers",
"SingleHop",
"Web Africa Proxy",
"OVH Systems",
"DFW Datacenter",
"MTW.RU dedicated/hosting servers",
"JSC Mediasoft ekspert",
"fast IT Colocation",
"Gmo Cloud America",
"Fiber Upload Srl",
"myLoc managed IT AG",
"Simply Transit Ltd",
"Hetzner Online AG",
"Hosting Solutions International",
"ZettaGrid",
"HOSTING90 systems s.r.o.",
"ETB",
"QuickPacket, LLC",
"Ubiquity Server Solutions Los Angeles",
"Information Technology Company (ITC)",
"Interprovider Limited",
"Multacom Corporation",
"OVH Ltd",
"Enzu",
"Hurricane Electric",
"ANEXIA Internetdienstleistungs GmbH",
"Cogent Communications",
"Iomart Hosting Limited",
"Cloud Customers",
"Colo at 55, LLC",
"ColoCrossing",
"Psychz Networks",
"Server Axis Corporation",
"Dedicated Server Hosting",
"Conjoinix Technologies Pvt. Ltd.",
"Server Block",
"Query Foundry, LLC",
"GHOSTnet GmbH",
"EasyTech",
"DataPipe",
"FASTNET",
"ServeTheWorld AS",
"HugeServer Networks, LLC",
"Private Enterprise Firma Fenix VT",
"UK Dedicated Servers Limited",
"Unix-Solutions BVBA",
"LeaseWeb",
"IPTelligent LLC",
"SoftLayer Technologies",
"Softlayer",
"SoftLayer Dutch Holdings B.V.",
"Server Pronto",
"inAsset Networks, S.L.",
"Free SAS",
"FD Networks",
"Redstation Limited",
"Host-telecom-net",
"SingleHop BV",
"Hosting Internet Hizmetleri Sanayi ve Ticaret Anon",
"DirectSpace Networks, LLC.",
"Portlane Networks AB",
"Transip B.V.",
"Interserver",
"Webhosting.Net",
"Ubiquity Server Solutions Seattle",
"Incero LLC",
"Ninefold",
"Solar VPS",
"Private Layer Inc",
"Katalyst Partners, LLC",
"OVH SAS",
"Infinite Technologies Limited",
"Microsoft Corporation",
"Silicon Valley Web Hosting",
"Wowrack.com",
"WebNX",
"AltusHost B.V.",
"NetVision",
"FortressITX",
"Hosting Services",
"Input Output Flood LLC",
"Columbus Networks USA",
"HostDime.com",
"SupremeBytes,LLC",
"Powerhouse Management",
"Hostingsource",
"EBL Global Networks",
"Database by Design, LLC",
"CtrlS Datacenters",
"Carat Networks",
"Fast Serv Networks, LLC",
"Kvchosting.com LLC",
"WeHostWebSites.com",
"Ubiquity Server Solutions Dallas",
"B2 Net Solutions",
"RackCentral Pty Ltd",
"Ubiquity Server Solutions New York",
"Privax Limited",
"Unlimited Net, LLC",
"Google",
"Google Cloud",
"HOST1PLUS Brazil",
"Limestone Networks",
"Avante Hosting Services",
"iWeb Technologies",
"Hosting Solutions",
"Kddi Corporation",
"Secured Servers LLC",
"Sean Isley",
"eNET",
"Nobis Technology Group, LLC",
"iWeb Technologies",
"Ubiquity Server Solutions Atlanta",
"WANSecurity",
"Choopa, LLC",
"Angel Drops",
"Ubiquity Server Solutions New York",
"Netrouting",
"EGIHosting",
"Steadfast Networks",
"Continuum Data Centers, LLC.",
"Open Computer Network",
"VolumeDrive",
"Hostwinds LLC.",
"Hostwinds LLC",
"Sharktech",
"Take 2 Hosting",
"Netelligent Hosting Services",
"HostRocket Web Services",
"TELECOM ITALIA SPARKLE S.p.A.",
"ServiHosting Networks S.L.",
"EGIHosting",
"Oversun Ltd",
"Internet-Hosting Ltd",
"OneAsiaHost",
"Megahostasn Mega Host Limitedb",
"Global Crossing",
"Gigas Hosting Usa, LLC",
"Gigas Hosting S.l",
"Gigas Hosting S.l.",
"HostDime.com.br Data Center",
"AltusHost",
"Hostwinds LLC.",
"Kvchosting.com LLC",
"Privax LTD",
"HP Hosting",
"Felicity Netbrella Corporation",
"Astute Hosting",
"Avante Hosting Services",
"NTT Network Core in LE hosting",
"WeHostWebSites.com",
"Melbourne Server Hosting Ltd",
"Level 3 Communications",
"Oversun Ltd",
"Iliad Hosting",
"Free SAS",
"Online S.a.s.",
"RapidSwitch Ltd",
"Iomart Hosting Limited",
"AltusHost Sweden Network",
"NOC4Hosts",
"NewMedia Express Pte Ltd.",
"Singapore Web Hosting Se",
"ServiHosting Networks S.L.",
"Unlimited Web Hosting UK LTD",
"RamNode LLC",
"jane m martin",
"Servepath",
"The Optimal Link Corporation",
"Poundhost customer server",
"Simply Transit Ltd",
"CrystalTech Web",
"Black Oak Computers Inc - Miami",
"Ericyhost - Ericsson North America Managed Service",
"Hosteam S.c.",
"XLHost.com","Megahostasn Mega Host Limited",
"Allhostshop.com",
"Conectiva",
"Hosting Operator eServer.ru Ltd.",
"Serverhousing - Hosting - IT-Services",
"Ovh Hosting Oy",
"Hostemo Technology Sdn Bhd",
"Rackspace Hosting",
"nLayer Communications",
"GIGLINX",
"DurableDNS, LLC",
"EGIHosting",
"Host Virtual",
"Reliablehosting.com",
"Megahostasn Mega Host Limited",
"CrystalTech Web Hosting",
"Hostemo Technology Sdn Bhd",
"WestHost",
"Megahostasn Mega Host Limited",
"FranceCentralHosts",
"Real Hosts Limited",
"Cloudhost Limited",
"Biznes-Host.pl sp. z o.o.",
"Myhosting",
"JaroNet s.r.o., Hostim",
"Hostspace - Hostspace Networks LLC",
"NexteCloud L.L.C.",
"Mochahost.com",
"Host Europe GmbH",
"SiteNet Host",
"HostForWeb",
"NewMedia Express Pte Ltd.",
"Hostdime.com UK client",
"HostDime Limited",
"Neo Telecoms S.A.S.",
"Gigabit Hosting",
"Fornex Hosting S.L.",
"LayerIP - UK hosting division infrastructure",
"Cyberghost S.R.L. IP Network",
"RimuHosting",
"TM-VADS DC Hosting",
"NTT Europe Web Hosting - Frankfurt",
"HOST1PLUS VPS servers at Brazil location",
"Fasthosts Internet Limited - UK\'s largest web host",
"Fasthosts Internet",
"Fast Hosts LTD",
"NTT Europe Web Hosting - Frankfurt",
"AT&T Webhosting Amsterdam IDC",
"Host-Telecom.com",
"OVH Hosting Limited",
"GoDaddy.com, LLC",
"Web Phase Limited",
"Go Daddy Netherlands B.V.",
"VegasNAP, LLC",
"Black Oak Computers Inc - San Francisco Reliablehosting.com",
"TC TEL hosting",
"QuadraNet",
"DataShack, LC",
"Nobis Technology Group, LLC",
"Ubiquity Server Solutions Chicago",
"Nobis Technology Group Phoenix",
"Iptripleplay Ltd",
"George Kontostanos (Planet Maars)",
"Tranquil Hosting",
"Sophidea",
"Alpheus Data Services, L.L.C.",
"incubatec GmbH - Srl",
"Incubatec GmbH - SRL",
"Freenet Ltd.",
"Triple T Internet Company Limited",
"PleskLogin Net",
"Microglobe LLC",
"HOSTINGER",
"Microsoft Hosting",
"Gandi Dedicated Hosting Servers",
"AFNCA",
"DME Hosting LLC",
"TM VADS DC Hosting",
"UDomain Web Hosting Company",
"Portland Internet Hosting LLC",
"JMF, Web Hosting Company, Japan",
"GorillaServers",
"Directspace Networks",
"XL Internet Services B.V.",
"InstaVPS",
"Digiweb ltd",
"Trit Networks, LLC",
"Sc Fx Software Srl",
"Joyent",
"Telecom Argentina S.A.",
"Pegtechinc - Peg Tech",
"LRG, Inc.",
"Infodoor Networking (Pty) Ltd",
"CMC Telecom Infrastructure Company",
"Antonio Santos",
"AS JSC KazTransCom",
"Nobis Technology Group, LLC",
"UpCloud Cloud Servers",
"Crissic Solutions, LLC",
"Sigmatic Oy",
"Netinternet Bilgisayar ve Telekomunikasyon San. ve",
"Turnkey Internet",
"AUNA - CTC",
"Voxel Dot Net",
"VPS Cheap",
"ReInfoCom Ltd.",
"Rackspace Cloud Servers",
"HostHatch, Inc",
"SolidHost",
"proXPN Direct LLC",
"Black Oak Computers Inc - San Francisco",
"Host-Telecom.com s.r.o.",
"Nexeon Technologies",
"jan-erik_hintikka",
"Cloud Servers Cell 0001-0003 IAD3",
"Cloud Servers (ORD)",
"Rackspace Cloud Servers IP Space",
"23Media GmbH",
"Inmotion Group",
"AT&T Synaptic Cloud Hosting",
"Aruba S.p.A.",
"Serveryou",
"Krypt Technologies",
"Yomura Corporation",
"Digital United Inc.",
"China Unicom Zhejiang",
"D-hosting die Rackspace & Connectivity GmbH",
"Customer VPS services located in Falkenberg",
"Neterra servers infrastructure",
"Neterra Ltd.",
"Server Serveis i Productes Informatics, S.L.",
"IP ServerOne Solutions Sdn Bhd",
"Syniverse Technologies, LLC",
"Hosted Data Solutions, LLC",
"Data Return",
"KDDI Web Communications Inc.",
"Colo4, LLC",
"EHOSTIDC",
"Cloudsigma Ag",
"Googlebot",
"ilika.net LLC",
"Hexaware Technologies Limited",
"IT7 Networks",
"AWB-NET Agnieszka Barzdo",
"phpwebhosting.com, LLC",
"ioko customer hosting block 2 - TH",
"Webhostingbuzz.com",
"Fastvps Eesti Ou",
"Black Fox Limited",
"CentriLogic",
"Centrilogic",
"CloudRadium L.L.C",
"Dimension Data Cloud Solutions",
"ColoUp",
"SolidTools Technology",
"LeaseWeb B.V.",
"Microsoft bingbot",
"1&1 Internet",
"Digital Ocean",
"DigitalOcean",
"Privax",
"KW Datacenter",
"ReliableSite.Net LLC",
"Mileweb PacketExchange",
"Mileweb",
"Hostspace Networks LLC",
"ClearDDoS Technologies",
"Hostlocation Ltda",
"S.C. Everhost S.R.L.",
"HOST1PLUS hosting services. Brazil.",
"Astimp Consulting SRL",
"Conjoinix Technologies Pvt. Ltd.",
"Global Frag Networks",
"Websecure",
"Landis Holdings",
"Conceptual Mindworks",
"Cbeyond Communications",
"Friedlander Cherwon Capper LLP",
"TNCI",
"IPNetZone",
"Airband Communications",
"Zimcom Network Solutions",
"OLM, LLC",
"DC74 LLC",
"Virtuzo",
"Vivid Hosting",
"Burstfire Networks Ltd",
"INTERNEXT 2000 s.r.o.",
"Micfo, LLC.",
"Simply Transit Ltd",
"IncoNet Data Management sal",
"Microsoft Azure",
"Microsoft Corp",
"Netmagic Datacenter Mumbai",
"Netmagic Datacenter",
"Net Design SRL",
"DoclerWeb Kft.",
"1&1 Internet AG",
"Virtual Server hosting",
"Makonix SIA",
"Atlantic.Net - Dallas, LLC.",
"GlobalNet",
"SFR",
"VPS-clients",
"Pallada Web Service LLC",
"Long Van Soft Solution JSC",
"GMO Internet, Inc.",
"Hexabyte",
"SoftLayer Dutch Holdings BV",
"GigaSpaces Technologies",
"Host Palace Internet Services",
"Serverius Holding B.V.",
"DFI Service SA",
"INTERNEXT 2000 s.r.o.",
"Cogetel Online",
"Dacentec",
"Telentia Enterprise Client",
"Anonymous Proxy",
"CIS NEPHAX",
"VooServers Ltd",
"Zen Systems Hosting",
"Zen Systems A/S",
"MadeIT",
"Azuria",
"RackCentral Networks",
"Gigabit Hosting Sdn Bhd",
"Telentia",
"B2 Net Solutions",
"Privax Limited",
"Ubiquity Server Solutions Atlanta",
"iWeb Technologies",
"NetStack-AS",
"Digital Energy Technologies Chile Sp",
"Netbrella Corporation",
"CIS NEPHAX",
"Micfo, LLC.",
"InstaVPS",
"Waveform Technology, LLC",
"THOR Data Center ehf",
"SC Fastweb SRL",
"SIS Group Datacentre Sydney",
"iomart Group PLC",
"Iomart Cloud Services Limited",
"Contabo GmbH",
"Net-style Atarim Ltd",
"Citylink Fiber Holdings",
"GINERNET",
"Deninet KFT",
"Core-Backbone GmbH",
"Ecatel Network",
"Oy Crea Nova Russia LTD",
"Private Layer Inc",
"Netco Solutions Limited",
"Ecatel LTD",
"Uab Duomenu Centras",
"IPSERVERONE - Colocation & Dedicated Servers",
"BetterServers (BETTE-38)",
"Ace Data Centers",
"Xt Global Networks Ltd.",
"Dedicated Servers Ip Pool",
"ZAO National Telecommunications",
"Net for VPS servers.",
"United Gameserver GmbH",
"Sub-Allocation myLoc",
"VDC",
"VpsQuan L.L.C.",
"XeVPS L.L.C",
"Sun Network (Hong Kong) Limited",
"VPSLAND",
"Global Net Access, LLC",
"Webfusion Internet Solutions",
"VPS",
"Hurricane Internet",
"tw telecom holdings",
"WWW Ibercom Net",
"National Computer Systems Co Ltd",
"HiNet",
"MTN Network Solutions Pty Ltd",
"Procono S.A.",
"Soltia Consulting SL",
"Power Up Hosting",
"VMware",
"TekSavvy Solution",
"Leaseweb Germany GmbH",
"NewMedia Express Indonesia Operation",
"TurkNet Iletisim Hizmetleri A.S.",
"IP-Converge Data Center",
"IP-Converge, Internet Data Center.",
"HOST1PLUS OpenVZ VPS services.",
"Netstack Ltd",
"Digital Energy Technologies Chile SpA",
"UK2 - Ltd",
"OppoBox",
"Leaseweb Asia",
"Leaseweb Deutschland GmbH",
"LeaseWeb Network B.V.",
"LeaseWeb Netherlands B.V.",
"Secure Internet LLC",
"Infolink Global Corporation",
"CyrusOne LLC",
"Websitewelcome.com",
"Terrenap Data Centers",
"Websense Hosted Security Network",
"SurfControl",
"FortaTrust USA Corporation",
"Microsoft",
"FreeBit Co.,Ltd.",
"MAROSNET Telecommunication Company LLC",
"Mojohost VL401 3NGNETWORKS",
"Mojohost",
"Unithost Internet B.V.",
"Netorn, hosting & colocation",
"Netorn LLC",
"Alphaomegahosting-colo",
"UK Webhosting Ltd",
"Fast2host Ltd",
"FranTech Solutions",
"Locaweb Servi xE7os de Internet S/A",
"Query Foundry, LLC",
"VTX Services SA",
"InfraDMS",
"Micfo, LLC.",
"Miami Cloud Hosting",
"OppoBox",
"AccelerateBiz",
"Host1free.com - Free Hosting & Vps & Cloud-service",
"Trusov Ilya Igorevych",
"Transit Telecom LLC",
"Atomohost LLC",
"AVAST Software s.r.o.",
"Unified Layer",
"Peer 1 Network (USA)",
"B2 Net Solutions VPS CLIENTS",
"Joe\'s Datacenter, LLC",
"Roya Hosting LLC",
"HostMySite",
"World Wide Web Hosting, LLC",
"Serverdroid LLC",
"OOO Network of data-centers Selectel",
"SourceDNS",
"Ideal Hosting Sunucuninternet Hiz. Tic. Ltdsti",
"Clouditalia Telecomunicazioni S.p.A.",
"Idealhosting Sunucu Internet Hiz. Tic. Ltd Sti",
"Mahsum Celik trading as ServerPlus Internet Sunucu",
"Net3",
"Aventice LLC",
"QuickPacket, LLC",
"GOSTARESH-E-ERTEBATAT-E MABNA COMPANY (Private Joi",
"Datacenter IP, LLC",
"ColoCenter b.v.",
"HP Hosting",
"VMware",
"VMware UK Ltd.",
"Liquid Web",
"Hetzner Online GmbH",
"Hetzner Online AG",
"Tomato Web (PVT) Limited",
"Advan Technologies LLC",
"IBM Corporation",
"ThePlanet.com Internet Services",
"M5 Computer Security",
"7Host Web Hosting",
"Solido Hosting A/S",
"Iliad Hosting",
"Hosting Services",
"Hostinger International Limited",
"Avante Hosting Services",
"Dedicated Server Hosting",
"Iomart Hosting Limited",
"Hostspace Networks LLC",
"HP Hosting",
"HostDime.com",
"7Host Web Hosting",
"Spartan Host",
"Host Sailor Ltd.",
"HostPalace Network Services",
"HostHatch",
"Web hosting provider and ISP connectivity.",
"HostUS",
"HostUS Solutions LLC",
"Hostigation",
"JaroNet s.r.o., Hostim",
"Hostkey B.v.",
"HostDime.com.mx S.A. de C.V.",
"HostDZire Web Services Pvt. Ltd.",
"Aruba GmbH Cloud Network",
"Hostspace Networks LLC",
"UOL Cloud Computing",
"Host Lincoln Limited",
"HostDime Data Center Services PVT",
"Nodistro IT, LLC",
"SupremeBytes, LLC",
"CloudMosa",
"DedFiberCo",
"Cloud Sigma",
"UPC Ceska Republica, s.r.o.",
"UPS Austria Gmbh",
"WBS Connect, LLC",
"Areti Internet Ltd",
"Falco Networks B.V.",
"Alentus Corporation"
"Leaseweb Asia Pacific pte. ltd.",
"Iomart",
"RamNode LLC",
"Cncservers LLC",
"SimpleLink LLC",
"Cty co phan ha tang vien thong CMC",
"layer 2 -Customer Nework of VTDC",
"Optimate-Server",
"M247 Ltd",
"180Servers.com",
"Oso Grande IP Services, LLC",
"KeepYourIP",
"C7 Data Centers",
"DataCenter One",
"Trend Micro Incorporated",
"Athenix",
"River City Internet Group (Primary Networks)",
"Arvixe, LLC",
"Quantil",
"Easyhost BVBA",
"Cyber Futuristics India Pvt",
"CoreSpace",
"Micfo, LLC.",
"Onvoy",
"DepoDataCenter",
"Netsoftware LLC",
"Kalamazoo RESA",
"RACK59 Partners, LLC",
"Drake Holdings LLC",
"Handy Networks, LLC",
"Hosting Solution",
"Univera Network",
"InMotion Hosting",
"A2 Hosting",
"ComfortHost",
"Host Wagon LLC",
"Peer 1 Dedicated Hosting",
"Server Central Network",
"White Sands Hosting",
"QuickWeb Technologies LLC",
"Server Central Network",
"Telx",
"Reprise Hosting",
"Eonix Corporation",
"Lowest Host/Empire Technology LLC",
"EvolveIP, LLC",
"New Dream Network, LLC",
"Link Telecom LLC",
"Siteserver Hosting",
"Hostway Corporation",
"UK2.NET",
"OC Hosting",
"Virtual Internet (UK) Limited",
"JCHost Internet Services, LLC",
"Arachnitec",
"HostSlim BV",
"Total Server Solutions L.L.C.",
"M247",
"Micron21-Melbourne-Datacentre",
"Petersburg Internet Network",
"PenTeleData",
"hiQ Data Corporation",
"Six Degrees Managed Data Limited",
"Nexlogic Telecommunications Network",
"Automated Data Systems",
"4D Data Centres",
"DataYard",
"Windstream Hosted Solutions, LLC",
"AFConnect",
"Melbourne Server Hosting",
"QWK.Net Hosting",
"Hostgator.com LLC",
"Portlane Networks",
"SIMPLEXHOST-AS",
"Alexhost Srl",
"Normhost Sarl",
"Simplexhost sp. z o.o.",
"UK Webhosting",
"Axxess Networks",
"Afrihost",
"Elastichosts Ltd",
"Root Level Technology, LLC",
"Ransom IT Trust",
"MATI",
"HostRocket.com",
"DotBlock.com",
"Hosting Shop",
"DATAREALM Internet Services",
"Interscale",
"Crucial Paradigm Pty Ltd",
"Interhost Communication Solutions",
"Resilans AB",
"Areti Internet",
"IPVanish",
"Bandcon",
"Mudhook Marketing",
"Mudhook Marketing Ashburn IP Block",
"Eweka Internet Services B.V.",
"Highwinds Network Group",
"CityLink Fiber Holdings, Inc.",
"netirons",
"Fevvo",
"CachedNet LLC",
"Contina",
"Border Technology, LLC",
"Bezeq International",
"Hakan Erdem",
"Inter Connects Inc",
"Core NAP, L.P.",
"Micro Incorporated",
"Pp Sks-lugan",
"home.pl S.A.",
"Virtual Citadel Inc.",
"BroadRiver Hosting",
"BroadRiver",

"1st Class Hosting, LLC",
"A2 Hosting",
"ACENS_AS (Spain) Hosting, housing and VPN services",
"Activehost-ru",
"ADMHOST",
"Adulteuhost",
"Advancedhosters",
"AGARIK provide WEB, Servers Hosting and dedicated",
"Altushost-net",
"Arkbhosting",
"As-cloudhosting",
"ASBHOST B-Host.it Internet Services",
"ASEUHOST",
"Asghostnet",
"Astute Hosting",
"Asvpshosting",
"Atomohost-dc1",
"ATT-EMEAIDC-AMS1-AS AT&T Webhosting Amsterdam IDC",
"Avante Hosting Services",
"Besthosting",
"Beyond Hosting, LLC",
"BHOST",
"Bird Hosting",
"By-hosting",
"Canhost",
"Carpathia Hosting",
"Content Provider and Hosting Services",
"Corporacion Hostarica S.A.",
"Cybercom Hosting",
"Danhost-dk",
"Datenhosting",
"Dedicated servers, colocation, hosting.",
"DGCHost.Net",
"Dhosting-net",
"Dialhost Internet Ltda.",
"Digiweb Advanced Hosting Limited",
"Dinahosting",
"DNHOST",
"DREAMHACKHOSTING Dreamhack - The worlds largest co",
"Easyhost Solution Limited",
"Easyhost-colo",
"EGIHosting",
"Elitehosting",
"Excellent-hosting",
"Extrahost",
"Extrahost-sk",
"Fasthost",
"FERAL Feral Hosting",
"Flamehosting",
"FREEHOST",
"Gigabit Hosting Sdn Bhd",
"GIGAHOST",
"Globalhost-bosnia",
"Globalhosting",
"GMHOST",
"GPLHost LLC",
"Greenhost",
"Grupohost Comunicacao Multimidia Ltda",
"H4hosting",
"Hoopla Hosting Limited",
"Host Color",
"Host Duplex, LLC",
"Host Networks",
"Host Revenda",
"Host Virtual",
"Host-telecom",
"Host1Plus",
"Hostasaurus",
"Hostbasket-backbone",
"Hostcamp",
"Hostcentral",
"HostDime.com",
"HostDime.com.br Data Center",
"Hostdzire",
"Hosteam",
"Hosted Backbone",
"Hosterov",
"Hosteurope",
"Hostex Hostex",
"Hosting operations",
"Hosting Services",
"Hosting Solution",
"HOSTING90 systems s.r.o.",
"Hostinger",
"Hostiserver",
"Hostit-as-nn",
"Hostkey",
"HOSTLINE",
"Hostlocation Ltda",
"HostManager",
"HostMySite",
"HOSTNET",
"Hostpoint",
"Hostpro",
"HostRocket.com",
"Hostserver GmbH",
"HOSTSLIM",
"HostUS",
"Hostway Corporation",
"Hostway Services",
"Hostwinds LLC.",
"HYPERHOSTING Georgios Vardikos trading as HYPERHOS",
"Ihost Solutions Pty",
"iHosting Servicios Internet Ltda.",
"INHOSTED",
"InterBS S.R.L. (BAEHOST)",
"Interhost",
"Interhost Pacific Pty Ltd t/a Intervolve.",
"IPHOST .GR IpDomain",
"Ippon_hosting",
"ISM eCompany Hosting Services",
"ISP and web hosting.",
"Itshosted",
"JCHost Internet Services, LLC",
"Kvchosting.com LLC",
"LCHOST",
"Lightpoint Colocation & Hosting LLC",
"LINQHOST",
"LLHOST",
"Localhost_as",
"Lowest Host/Empire Technology LLC",
"Managedhosting",
"Media-Hosts",
"MIROHOST Web hosting, datacenter and domain names",
"Mojhost-eu",
"MOJOHOST",
"Multihost",
"Multihousehosting",
"My Hosted Internet",
"My-hosted-internet",
"Netelligent Hosting Services",
"Nethostingtech",
"Network of IBM E-business Hosting Delivery",
"NSI Hosting",
"OC Hosting",
"Packet Host",
"Peak Web Hosting",
"Peterhost-piter",
"Pidginhost",
"PRTSYSTEMS PRT Systems Ltd (Clearhost Transit AS)",
"QHOSTER",
"QUADHOST",
"QWK.Net Hosting",
"Rackhosting",
"Rackspace Hosting",
"RAM Host",
"Realhosts",
"Redhosting",
"Reliable Hosting Services",
"Reliablehosting.com",
"Rethem Hosting LLC",
"Routed-Hosting",
"Rucenter-hosting",
"Sadecehosting-Com",
"SAFEHOSTNET Colocation center in Geneva",
"Safehosts",
"SiteHost New Zealand",
"Skhosting-eu",
"Spartanhost",
"Superhost-pl",
"SureHosting Internet Solutions",
"Systemhost",
"Telx Hosting",
"Terrahost_as",
"Tranquil Hosting",
"Tsukaeru.net, Web Hosting Company, Japan",
"UDomain Web Hosting Company",
"UK Dedicated Servers, Hosting and Co-Location",
"UKHOST4U",
"Unic-hosting",
"UNITEL Unitel - Fast reliable hosting",
"Unithost",
"Velocihost",
"Ventelohosting",
"Venzohosting",
"Vivid Hosting",
"Vmhosting-ua",
"Vmhosts-london",
"Voicehost",
"Vshosting",
"WEB4CE webhosting",
"WestHost",
"White Sands Hosting",
"XHOSTING",
"Zappie Host",
"Zglobalhost Ltda.",
"Zimba Host",
"Anycast cloud",
"Apptocloud",
"Arubacloudltd",
"As-cloudhosting",
"As-cloudity",
"As_tcpcloud",
"BELCLOUD",
"Bigstep-cloud",
"Bulletproof, Mission Critical Cloud",
"Cisco Systems Cloud Division",
"Cloud 9 Internet",
"Cloud Comunicacoes Ltda Me",
"Cloud Earth Pty",
"Cloud Registry Pty",
"Cloud Scale Limited",
"Cloud Xpress",
"CLOUD-DK",
"Cloud.IT Services Limited",
"Cloud2nube, S.A.",
"CloudAccess.net, LLC",
"CLOUDATA",
"Cloudcenter",
"CLOUDCORE CloudCore.IO",
"Clouddc",
"Cloudddos Technology Co.,limited",
"Merit Network",
"DHMS Ltd",
"FORTHnet SA",
"BigTip",

"Cloud Provider USA, LLC.",
"E-Com Cloud Solution Co.",
"Forcepoint Cloud Limited",
"Cloud People Pty",
"Cloud Hosting Co",
"Thecloud Limited",
"Shanghai UCloud Information Technology Company Lim",
"PT Cloud Hosting Indonesia",
"Cloudnyne",
"Cloud IT Pty Ltd",
"Cloudhost Cloudserver",
"cloudsky superfast broadband and services Pvt",
"Cloud Himalaya Pvt",
"ITonCloud",
"Shanghai Zople Cloud Computing Technology Co.,Ltd.",
"Suzhou super cloud network technology co.",
"Beijing Sankuai Cloud Computing Co.,Ltd.",
"CloudSource IT Limited",
"Guizhou Baishan Cloud Technology Co.",
"Seven Hills Cloud Technology Private Limited",
"Safehouse Cloud Inc",
"MADDISON, THOMAS IAN T/A On A Cloud",
"CloudFlare",
"Cable DR Cloud Joint Venture",
"Minder Secure Cloud Services",
"Guizhou Wingcloud Bigdata Service",
"Safehouse Cloud PTE. LTD.",
"cloudtime",
"Cloudlasers Broadband",
"FiberHome Cloud Technologies Ltd.,Co",
"CorpCloud Pty",
"Imcloud Technology Company Limited",
"Cloudnet Communications Pvt",
"Hyscloud-jp",
"CloudLogix Pty",
"Chongqing Cloud Computing Investment&Operation Co.",
"Dimension Data Cloud Solutions",
"InterCloud",
"Tianjin new cloud network technology co.",
"LocalCloud Limited",
"LiveOps Cloud Platform, LLC",
"Tianjin green cloud network technology co.",
"NakiCloud",
"Cloud Operation Pvt",
"cloudvop.com",
"The Beijing the Cloud Public lnternet Technology C",
"Cloudovs Vietnam Technology Joint Stock Company",
"China Unicom Cloud Data Company Limited",
"CloudVsp",
"Cloud365 Australia Pty Limited",
"Cloudvis technology company limited",
"SimplerCloud Pte",
"Inhanced Cloud Pty",
"Cloudhost Limited",
"Beijing Kingsoft Cloud Internet Technology Co.",
"Cloud Telecom",
"ZNet Cloud Services",
"Beijing Expo Cloud Technology Co.",
"Bjcloudnet",
"Smart Cloud Service Co.",
"VeloCloud Networks Private Limited",
"Cloud.IT Services Limited",
"Cloud Registry Pty",
"Bignoise Cloud",
"Cloud Scale Limited",
"Cnergee Cloud Technology Solutions LLP",
"LIGHT CLOUD TECHNOLOGY",
"Liaocheng Dongchangfu District cloud Network Techn",
"Supersafecloud LLC",
"CHINA UNICOM CLOUD DATA COMPANY LIMITED Shanghai B",
"Foundation Cloud Services Limited",
"Cloudoip Pty",
"Liaoning sino cloud Information Technology Co.",
"Beijing Qichuangdongli Cloud Technology Co.",
"Cloud Shield",
"Shenzhen cloud network technology Co.",
"LeTV Cloud Computing",
"Guangdong Cloudbase Technology Co.",
"Cloud Hosting",
"Cloud Earth Pty",
"Shenzhen Qianhai cloud & Big data limited company",
"Zettagrid Cloud",
"VeloCloud Networks",
"Thundercloud Enterprise",
"Cloud Sigma",
"Cloud A",
"StormCloud Network (Canada) Incorprated",
"CloudAccess.net, LLC",
"Real Time Cloud Services LLC",
"Enteracloud Solutions",
"mClouds",
"Cloud Central Pty",
"CLOUD 7 WIRELESS NETWORKS Private Limited",
"Sempernet subsidiary of Coherent Cloud",
"Bulletproof, Mission Critical Cloud",
"Dimension Data Cloud Solutions Australia",
"CloudGenix",
"The Snow Cloud",
"Oracle Public Cloud",
"Apptocloud.com s.r.o.",
"CloudFlare Latin America S.R.L",
"Teccloud ServiÃ§os De Tecnologia Ahu Ltda.",
"CHILENETWORKS - Cloud Computing",
"Unixsis Servicos de Unix e Cloud - ME",
"Cloudun Information Technology (Beijing) Co.",
"NxtGen Datacenter & Cloud Technologies Pvt.",
"Cloud2nube, S.A.",
"Cloud Comunicacoes Ltda Me",
"The Network Cloud Limited",
"HK Mainstream Cloud Network Technology Limited",
"GreenClouds B.V.",
"Beijing CloudHosting Communications CO.,LTD",
"Beijing Unlimited Cloud Technology Co.",
"GMO Cloud",
"Netstack Cloud Services",
"Fortacloud",
"CLOUDMERGE CloudMerge B.V.",
"Green Cloud Technologies,LLC",
"dinCloud",
"NexCloud",
"TheNebulaCloud",
"Iqcloud SA De Cv",
"Cloud 9 Internet",
"Cloud-On-Demand",
"Liquidcloud",
"Cloud-Temple",
"CloudConnect Networks",
"SAS Intercloud",
"CloudBR Brasil",
"SOUNDCLOUD",
"Gmo Cloud K.k.",
"Beijing Eyun Cloud Network Technology Co.",
"Net Onboard Sdn Bhd - Quality & Reliable Cloud Hos",
"CLOUD.nl B.V.",
"Cloud Care s.r.l.",
"Cloudzilla BV",
"Vola by ExcomCloud S.L.",
"Excom cloud S.L.",
"Cloud Werkt BV",
"Cloudlayer8 Limited",
"Enolem Cloud Kft.",
"Pragma Cloud Limited",
"One Cloud Ltd",
"Pure Cloud Solutions Limited",
"cloudinfrastack, s.r.o.",
"Copaco Cloud B.V.",
"Cloud Unboxed Limited",
"Pacific Controls Cloud Services FZE",
"CLOUD & HEAT Technologies GmbH",
"Cloudwifi, Sl",
"Serviced Cloud Ltd",
"Telecoms Cloud Networks Limited",
"tcp cloud a.s.",
"Cloud DNS Ltd",
"Clouded Web Hosting Ltd",
"iGamingCloud Limited",
"Clouded Domain and Web Services LTD",
"Global Cloud Infrastructure Company Limited",
"Cloudeon Europe A/S",
"BUSINESSINCLOUD Sp. z o.o.",
"BelCloud Hosting Corporation",
"CloudMerge B.V.",
"swiss cloud computing ag",
"Cloudzme Fze",
"MTF Swiss Cloud AG",
"CloudScape Connect Ltd",
"iOnline Cloud B.V.",
"ProCloud AG",
"PersianGig Cloud Inc.",
"NG Cloud SAS",
"MivoCloud SRL",
"Cloud4all UG",
"Skytel. Cloud Phone LLC",
"rktcloud SPC",
"LLC Gigacloud",
"any.cloud A/S",
"RTCloud, LLC",
"Markley Cloud Services, LLC",
"CloudNET Services Limited",
"LLC Cloud Technologies",
"Dutch Cloud B.V.",
"Fiducial Cloud Sasu",
"CloudCall",
"Deluxe Mediacloud Ltd",
"OrtCloud GmbH",
"Belarusian Cloud Technologies JLLC",
"iNNOVO Cloud GmbH",
"CloudKleyer Frankfurt GmbH",
"Cloudhelix Limited",
"Cloud2 B.V.",
"OU cloud.ee",
"Arcipelago Cloud Srl",
"Cloud Laboratory Ltd",
"Codestone Cloud LTD",
"Cloudfinder Sweden AB",
"CloudScalers BVBA",
"Cloud Networks SIA",
"Cloudata SAS",
"Todo En Cloud Sl",
"CloudHosting SIA",
"Cloud Center Finland Oy",
"Bigstep Cloud Limited",
"Foxcloud Llp",
"Beeks Financial Cloud Ltd",
"Cloud Networking Communications S.L.",
"CorvisaCloud, LLC",
"Cloud Holding International inc",
"CLOUDWIFI",
"CloudfloorDNS",
"Cloud Carib Limited",
"Bright Cloud Technologies",
"UBX Cloud",
"Dakota Cloud Networks, LLC",
"Cloudera",
"Clouditalia",
"Cloudnet SRL",
"Cloudme2 Technologies LTD",
"Gr-anycast-dns-cloud",
"THECLOUD",
"Cloud9 Communications Ltd",
"ONCLOUD",
"NETCLOUD",
"BlueCloud",
"Forcepoint-cloud-emea",
"CloudFlare Africa",
"Hybrid Cloud Gateway Canada",
"SoloCloud",
"InterCloud Systems",
"Cloudwave",
"UOL Cloud Computing",
"Safehouse Cloud Inc for SG",
"TeamCloud Solution Sdn Bhd",
"Hitachi,Ltd., Cloud services Division",
"C2 Cloud Services, LLC",
"Cloud Seven",
"Cloud Xpress",
"NantCloud Services LLC",
"Cloudmark",
"TheSnowCloud",
"White Cloud Technologies LLC",
"Cloudsafe",
"UpCloud USA",
"Cloud Solutions LLC",
"CloudBuy PLC",
"CloudRadium L.L.C",
"Defender cloud international llc",
"NexteCloud L.L.C.",
"CLOUDHUB Tech. Co.Ltd.",
"Lead Cloud Information Technology Co.",
"Jiangsu Cloud Together Information Technology Co.",
"Jiangsu Cloud Ever Information Technology Co.",
"Talk A Cloud Limited",
"Cloud Plus Pty",
"VTG Cloud Limited",
"Cloudsigma Ag",
"Twentyone-cloud",
"CloudVPS B.V.",
"CloudVPS",
"AT&T Synaptic Cloud Hosting",
"ALSO Cloud Oy",
"Sys11 Cloud Services UG (haftungsbeschraenkt)",
"CloudConnX Limited",
"Netcloud AG",
"ASCLOUDATA",
"Cloudalize BVBA",
"Smartcom Cloud Integrator Srl",
"Iron Cloud S.A.",
"Ukcloud Ltd",
"Oveenet-cloud",
"GetClouder EOOD",
"Bandwidth and Cloud Services Group Ltd",
"Cloud Computing Corporation",
"cloud store network",
"Cloudie Limited",
"Red Cloud",
"92Cloud Technology Co., Limited",
"Guang Ming Cloud Media Culture Communication Co.,L",
"Guang Ming Cloud Computing Co.,Ltd",
"Shandong Inpor Parkson Cloud Computing Technology",
"Shenzhen Qianhai bird cloud computing Co.",
"Bei Jing Cloud Times Technology Co.,Ltd",
"Shandong Cloud Comb Culture CO.LTD",
"HK ThinkCloud Network Limited",
"Cloud Rely Limited",
"ChinaCloud (Beijing) Data Computing Co.,Ltd.",
"PT Indonesian Cloud",
"Cyber Cloud Shield Broadband Services Private Limi",
"Net Cloud Limited",
"Syscloud(BeiJing)Technology Limited",
"Hangzhou cloud information technology co.",
"Beijing Cloud-Ark Technology Co.,Ltd.",
"Tencent cloud computing",
"SonderCloud Limited",
"Fuzhou Kaopu Cloud Technology Co.",
"Cloudvnp.Inc",
"Dual Cloud Information Technology (Shanghai)",
"ConnektCloud Pty.",
"iland Cloud Pte.",
"Zhejiang Watone Cloud Data Technology Co.",
"Jiangsu Smart Cloud Co.,Ltd",
"Kung Fu Cloud Technology Limited",
"Guizhou Wing Cloud High Technology",
"Beijing Cloud Mind Technologies Co.",
"Huawei Public Cloud Service (Huawei Software Techn",
"CHINA UNICOM CLOUD DATA COMPANY LIMITED Hohhot Bra",
"Network Cloud Time Company",
"Ordos UniCloud Technology Co.",
"Beijing SpeedyCloud Technologies Co.,Ltd.",
"Beijing Auspicious Cloud Information Technology CO",
"Jiangsu Sanai Cloud Computing technology co ,LTD",
"Anhui Excellent Cloud Network Technology Limited",
"BZYUN Cloud computing & IOT Technology Co.",
"Cong ty TNHH cong nghe Cloudone",
"Quantum Cloud New Media Technologies Co.Ltd",
"Wuxi Cloud Times Information Technology Co., Ltd.",
"Lovecloud Networks",
"Zhongwei Cloud Fabric Network Technology Co.,Ltd.",
"Exabytes Cloud Sdn.Bhd.",
"CloudInnovation infrastructure",
"CHINA UNICOM CLOUD DATA COMPANY LIMITED Heilongjia",
"UCloud (HK) Holdings Group Limited",
"Fncloud",
"CloudSRV Limited",
"LinAn Cloud Win Data Technology Co.",
"ChunAN Watone Cloud Data Technology Co.",
"HangZhou LiCloud Data Technology Co.",
"Beijing Cloud Online Technology Co.",
"Ningbo cloud Workshop Network Technology Co.",
"Beijing Diyi cloud Information Technology Co.",
"Shaoxing Cloudunion Information Technology Co.",
"Beijing Associative Cloud Information Technology C",
"CloudMosa",
"Cloudddos Technology Co.,limited",
"Cloud Next Ltd",
"ViaCloud WLL",
"OrionVM Cloud Platform",
"Comwire Cloud Pty",
"Digital Cloud",
"cloudscale.ch AG",
"Cloud-Brokers IT-Services GmbH",
"CLOUDNAP",
"Triple C Cloud Computing Ltd.",
"McCloud.nl B.V.",
"Scalaxy Cloud",
"Digium Cloud Services, LLC",
"Sinoycloud Limited",
"Smart Cloud Hosting Uk Ltd",
"Clouditalia Telecomunicazioni S.p.A.",
"CloudIP LLC",
"Cloudworks",
"St. Cloud Hospital",
"DataPipe Cloud",
"Cloud South",
"Cloud Communications, LLC",
"Cloudnet",
"Server Cloud Canada",
"AOScloud, LLC.",
"Iomartcloud",
"CloudOps",
"Fiberax Networking&Cloud Ltd.",
"Cloudtroopers",
"Cloudglobal France SAS",
"Google Cloud",
"UPCLOUD",
"Pinnacle Cloud Solutions Limited",
"The Cloud Networks Germany GmbH",
"CLOUD4YOU",
"Orange Cloud for Business SASU",
"Forcepoint Cloud Ltd",
"The Cloud Simplified Limited",
"BELCLOUD",
"Cloud Builders SA",
"ArubaCloud Limited",
"Safe Swiss Cloud AG",
"The Cloud Networks Limited",
"Cloudpro LLC",
"Turbine Cloud Services LLC",
"CLOUD",
"HS Cloud LLC",
"Cloudmore",
"As-cloudhosting",
"vCloud AG",
"Cloud Group sp. z o.o. sp. komandytowa",
"Cloudbase",
"DIS Web-Cloud Hosting",
"Ascloudtechnology",
"The Cloud Networks",
"Clouds New Network LLC",
"LLC CloudSol",
"Cloud4com, a.s.",
"tzulo",
"Cequel Communications Holdings",
"Servers.com B.V.",
"Servers.com",
"HostRoyale Technologies Pvt Ltd",
"Total Server Solutions L.L.C.",
"Hostio Solutions",
"Elastichosts Ltd",
"AnMaXX France",
"AnMaXX Deutschland",
"AnMaXX Rossija",
"AnMaXX Nederland",
"AnMaXX UK",
"AnMaXX Canada",
"ComfortHost",
"Netstack Ltd",
"Interhost Communication Solutions Ltd.",
"LIGHT CLOUD TECHNOLOGY",
"iDBHosT Limited",
"Serverhosh Internet Service",
"TrionInfra Dedicated Server Solutions",
"AnMaXX France",
"VimpelCom",
"EstNOC Holland",
"Thor Group LTD",
"xtudio networks sl",
"eNET",
"server4you",
"Lionlink Networks",
"2020 Communications LLC",
"HopOne Internet Corporation",
"Nuclearfallout Enterprises",
"Scaleway",
"SysEleven GmbH",
"Media Temple",
"SpeedVM Network Group LLC",
"Madgenius.com",
"247 Europe SRL",
"WorldStream B.V.",
"NFOrce Entertainment B.V.",
"VA Colo",
"Tele Global NY",
"VA Servers",
"Biznet Networks",
"ennit server GmbH",
"Liteserver Holding B.V.",
"v-sys.org",
"Core Back Bone",
"ESTOXY OU",
"HZ Hosting Ltd",
"M247 Ltd M247 Ltd",
"Web2Objects LLC",
"ServerAstra Kft.",
"StackPath LLC",
"Belcloud LTD",
"SysEleven",
"Datacamp Limited",
"China Telecom SHAANXI province Cloud Base network",
"Servers-com",
"InterServer SA",
"GLOBALTELEHOST Corp.",
"GTHost",
"Oy Crea Nova Hosting Solution Ltd",
"GoHosted.eu LTD",
"Maxihost LLC",
"Hosting Services Inc",
"HostHatch LLC",
"Abelohost BV",
"NewMedia Express",
"Ready Server Pte",
"InterServer SA",
"PlusServer GmbH",
"UpCloud Ltd",
"Belcloud LTD",
"Cloud S P Sarl",
"Maxihost LTDA",
"Infortelecom Hosting S.L.",
"Hostway Deutschland GmbH",
"AFRIHOST OTHER",
"FREEHOST",
"Host1Plus Cloud Servers",
"hosttech GmbH",
"Globalhost d.o.o.",
"TerraHost",
"Host Universal Pty",
"Kaopu Cloud HK Limited",
"NeroCloud TLD",
"ServerMania",
"Weserve B.V.",
"Serverius Holding B.V.",
"UAB Cherry Servers",
"ennit server GmbH",
"InterServer SA",
"NewMedia Express",
"Spry Servers",
"profitserver",
"ServerAstra Kft.",
"Server-Ware GmbH",
"PE Freehost",
"Dedibox SAS",
"US Dedicated",
"GleSYS Internet Services AB",
"DediPath",
"EHOSTICT",
"DMZHOST",
"ServeTheWorld",
"SkylonHost",
"Filip Hruska",
"Hosting Ukraine LTD",
"Hosting technology LTD",
"NovoServe B.V.",
"Servihosting Networks",
"ORG-SNS2-RIPE",
"Ihor Hosting LLC",
"ServeTheWorld",
"Rack Sphere Hosting S.A.",
"Racks Central Network",
"RackNation",
"axgn",
"Security Firewall Ltd",
"Serverfield Co.",
"WeServe",
"Weserve BV",
"ServersAustralia",
"EHOSTICT",
"Cnservers LLC",
"Rack Sphere Hosting S.A.",
"Racks Central Network",
"RackNation",
"axgn",
"Security Firewall Ltd",
"Serverfield Co.",
"WeServe",
"Weserve BV",
"ServersAustralia",
"EHOSTICT",
"NovoServe B.V.",
"Artfiles New Media GmbH",
"HIVELOCITY",
"CariNet",

"The Infrastructure Group B.V.",
"Next Layer Telekommunikationsdienstleistungs- und",
"Sollutium EU LLC",
"KeFF Networks Ltd",
"Amarutu Technology Ltd",
"Markus Koch",
"SIA Latnet",
"SWAN, a.s.",
"F3 Netze e.V."




)

');
*/
$res = $mysqli->use_result();
//echo "Result set order...\n";
$line_count = 0;
$today = date("D M j G:i:s T Y");
$today_timestamp = date("Ymd-His");
$line = "# GEOIP2 ISP AND ORG CREATED $today \r\n\r\n";
$line .= "192.168.0.3/32 CFS $today|$today_timestamp\r\n";
/* ENTER MANUAL LINES HERE */
//$line .= "86.96.0.0/14 Emirates Hosting|Emirates Hosting\r\n";
//$line .= "51.15.0.0/17 Dedibox SAS|Dedibox SAS\r\n";
//$line .= "163.172.208.0/20 Dedibox SAS|Dedibox SAS\r\n";
//$line .= "193.36.236.0/22 DediPath|DediPath\r\n";
//$line .= "212.83.128.0/19 Dedibox SAS Scaleway|Dedibox SAS Scaleway\r\n";



while ($row = $res->fetch_assoc()) {
    $line .= "" . $row['network_cidr'] . " " . $row['isp'] . "|" . $row['organization'] . "\r\n";
	++$line_count;
}



//echo $line;
//exit;

//$line .= "23.116.226.35/32 inMotion Group $today|inMotion Group $today\r\n";
//$line .= "3.123.34.76/32 inMotion Group $today|inMotion Group $today\r\n";

$fp = fopen($filename, 'w');
fwrite($fp, $line);
fclose($fp);



echo "completed $line_count records";

